# My Project

This is a very simple Python script that is used as an example to demonstrate how Git controls the versions.


In [2]:
import numpy as np

A = np.random.randn(4,5)
print(A)

[[-0.94829099  0.20533808 -0.51846852  0.14768536  0.86178909]
 [-1.91217719  0.06630836 -0.52301974 -0.71615816  0.18053163]
 [-0.16755777 -0.47481696 -0.25851183  0.4665076  -0.05456717]
 [ 1.1226326   0.77816417 -0.01665286  1.42065943  0.14126105]]


In [4]:
B = np.ones((5,5))
print(B)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## This should appear in the new branch only.
